import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import Header from "./ui/header/Header";
import WithAOS from "./ui/withAOS/WithAos";

const urbanist = Urbanist({
  subsets: ["latin"], // Add other subsets if needed
  weight: ["400", "700"], // Specify the font weights you need
});

export const metadata: Metadata = {
  title: "Scafolding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <WithAOS>
          <Header />
          {children}
        </WithAOS>
      </body>
    </html>
  );
}
