import React from "react";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "../globals.css";
import "aos/dist/aos.css";
import Header from "../ui/common/header/Header";
import WithAOS from "../ui/withAOS/WithAos";
const Footer = React.lazy(() => import("../ui/common/footer/Footer"));

const urbanist = Urbanist({
  subsets: ["latin"], // Add other subsets if needed
  weight: ["100", "200", "300", "400", "500", "600", "700"], // Specify the font weights you need
});

export const metadata: Metadata = {
  title: "Scafolding",
  description: "Generated by create next app",
  icons: "/svgs/logolap.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="/assets/herocover.webp" as="image" rel="preload" />
      </head>
      <body className={urbanist.className}>
        <WithAOS>
          <Header />
          {children}
          <Footer />
        </WithAOS>
      </body>
    </html>
  );
}
